### PR TITLE
Update with new logos for 22.04

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

- Update /downloads page with new CoF and logos
- Update to Vanilla 3.2.0
- Update the nav to new CoF
- Update /brand with new tag logo
- Hide Ubuntu logo page until it is ready

## QA

- See that the above changes are there and the downloads lead to the svg assets

## Screenshots

image

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
QA:
- [ ] There is a lot of space between the menu items and the logo. Can that be removed? 
image

**Comment by anthonydillon** [comment]
Could you set the height of the label-logo so it aligns a little better? 
image

**Comment by bartaz** [comment]
> There is a lot of space between the menu items and the logo. Can that be removed?

As far as I understand from Lyubo this is meant to be like this for all the websites to have consistently the same with of logo area.

**Review by anthonydillon — APPROVED** [review]

**Comment by pmahnke** [comment]
I updated this a bit, removed the commented links and moved to the ubuntu logo on the /brand page...

image


I can't update the tag logo easily right now.

Also Thibaut approved the nav

**Pull request merged**
